import { assetPath } from "@/app/lib/site-path";

export type EventCategory = "Music" | "Wellbeing" | "Heritage" | "Community" | "Garden Bar";
export type VenueEvent = { id: string; slug: string; title: string; summary: string; description: string; date: string; endDate?: string; time: string; endTime?: string; category: EventCategory; image: string; imageAlt: string; price: string; location: string; access: string; featured?: boolean; eventbriteUrl?: string; verify?: boolean };
export const eventCategories: EventCategory[] = ["Music", "Wellbeing", "Heritage", "Community", "Garden Bar"];
const base = { access: "Access arrangements and the final event format must be confirmed with the organiser before booking.", verify: true };
export const events: VenueEvent[] = [
  { ...base, id: "sound-bath-jul", slug: "sound-bath-experience-july-29", title: "Sound Bath Experience", summary: "An immersive evening of sound and stillness beneath the open roof.", description: "Settle into the stillness of St Luke’s for a guided sound bath with Jake and Geniene. Bring something comfortable to lie on and let the space do the rest.", date: "2026-07-29", time: "17:30", endTime: "18:30", category: "Wellbeing", image: assetPath("/images/church-nave.jpg"), imageAlt: "View through the ruined nave towards St Luke’s tower and blue sky.", price: "Donation-based — booking details to verify", location: "Inside St Luke’s", featured: true },
  { ...base, id: "sound-bath-aug", slug: "sound-bath-experience-august-2", title: "Sound Bath Experience", summary: "A second chance to settle, listen and look up.", description: "A gentle sound-led session with Jake and Geniene in the unusual, open-air surroundings of St Luke’s.", date: "2026-08-02", time: "09:30", endTime: "10:30", category: "Wellbeing", image: assetPath("/images/church-roof.jpg"), imageAlt: "Open-roof interior of St Luke’s Bombed Out Church.", price: "Donation-based — booking details to verify", location: "Inside St Luke’s" },
  { ...base, id: "twelfth-night", slug: "twelfth-night", title: "Twelfth Night", summary: "Off the Ground Theatre brings Shakespeare’s comedy to one of Liverpool’s most unlikely rooms.", description: "A current-site programme listing retained as a local prototype. The production details, access information and booking destination must be confirmed before publication.", date: "2026-08-02", time: "17:00", endTime: "20:00", category: "Music", image: assetPath("/images/church-arch.jpg"), imageAlt: "St Luke’s tower framed by a weathered brick arch.", price: "Price to verify", location: "St Luke’s" },
  { ...base, id: "open-day", slug: "open-day-august-15", title: "Open Day", summary: "Come in for time to explore the building and gardens at your own pace.", description: "This open-day record converts the current site’s manually written opening schedule into the calendar. Exact hours must be confirmed before publication.", date: "2026-08-15", time: "11:00", endTime: "16:00", category: "Heritage", image: assetPath("/images/church-wall.jpg"), imageAlt: "The long red-brick wall and arches of St Luke’s.", price: "Free — hours to confirm", location: "Across the site" },
  { ...base, id: "makers-market", slug: "makers-market-august-16", title: "Makers Market", summary: "A relaxed day of local makers in the gardens.", description: "A local prototype record based on the Makers Market date shown in the current open-day schedule. Times and traders must be confirmed.", date: "2026-08-16", time: "11:00", endTime: "17:00", category: "Garden Bar", image: assetPath("/images/garden-bar.jpg"), imageAlt: "Visitors enjoying the Garden Bar beside the church.", price: "Free entry — times to confirm", location: "Gardens" },
  { ...base, id: "savera", slug: "savera-uk-culture", title: "Savera UK — Culture at the Bombed Out Church", summary: "A free, family-oriented afternoon of culture, workshops and performances.", description: "This listing is retained from the current site. Please check its format, partners and final visitor information before publishing.", date: "2026-08-29", time: "13:00", endTime: "16:00", category: "Community", image: assetPath("/images/garden-crowd.jpg"), imageAlt: "Crowd gathering in the sunny garden beside St Luke’s.", price: "Free", location: "St Luke’s" },
];
export const formatEventDate = (event: VenueEvent, options?: Intl.DateTimeFormatOptions) => { const start = new Date(`${event.date}T12:00:00`); const end = event.endDate ? new Date(`${event.endDate}T12:00:00`) : undefined; const formatter = new Intl.DateTimeFormat("en-GB", options ?? { weekday: "short", day: "numeric", month: "short" }); return end ? `${formatter.format(start)} – ${formatter.format(end)}` : formatter.format(start); };
export const formatTime = (time: string) => time.replace(":", ".");
